project_name: test
release:
  github:
    owner: kuetemeier
    name: test
  draft: true
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
build:
  binary: test
  main: .
  ldflags: -s -w -X github.com/kuetemeier/test/config.buildTime={{.Date}} -X github.com/kuetemeier/test/config.gitHash={{.Commit}} -X github.com/kuetemeier/test/config.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
  env:
    - CGO_ENABLED=0
archive:
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
